### PR TITLE
Guess wakatime-cli-path if it's not set.

### PR DESCRIPTION
**Pull request by yewton**
Related issues: #16 #12 #6 
pyenv and Homebrew require special care of `wakatime-cli-path` .

### CODE REVIEW

**Comment by alanhamlett** [comment]
What about the existing `wakatime-python-bin` variable for customizing the python path in user's `init.el`? Does this commit make `wakatime-python-bin` irrelevant?

**Comment by yewton** [comment]
`wakatime-python-bin` specifies where the python binary is(e.g. `/usr/local/bin/python` ).
`wakatime-python-path` is for `PYTHONPATH` environment variable(e.g. `/usr/local/Cellar/wakatime-cli/4.0.14/libexec/lib/python2.7/site-packages` ).

**Comment by yewton** [comment]
With Homebrew:

```
$ cat `which wakatime`
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/wakatime-cli/4.0.14/libexec/lib/python2.7/site-packages" exec "/usr/local/Cellar/wakatime-cli/4.0.14/libexec/bin/wakatime" "$@"
```

With pyenv:

```
$ cat `which wakatime`
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/yewton/.pyenv"
exec "/usr/local/Cellar/pyenv/20151124/libexec/pyenv" exec "$program" "$@"
```

This PR supports both case.

**Comment by alanhamlett** [comment]
Awesome, thank you!

**Pull request merged**
