### PR TITLE
Add instructions for Spacemacs

### PR DESCRIPTION
**Pull request by yihuajack**
Add instructions for Spacemacs.
Relate to solving wakatime [#97](https://github.com/wakatime/wakatime/issues/97).

### CODE REVIEW

**Comment by Anton-Latukha** [comment]
That would mean there is 2 sources of truth to maintain.

It is probably enough to give URL to the official Spacemacs docs on this stuff: https://develop.spacemacs.org/layers/+web-services/wakatime/README.html.

I also had problems using Customize menus in Emacs together with having Spacemacs configuration, and IDK is advising using them in Spacemacs is the way.

**Comment by alanhamlett** [comment]
@yihuajack what do you think about updating this PR where the instructions link to [Installing WakaTime with Spacemacs](https://develop.spacemacs.org/layers/+web-services/wakatime/README.html) docs instead?

**Comment by Anton-Latukha** [comment]
At this point Spacemacs distro essentially became rolling, so that is why it is a link to `https://develop.spacemacs.org/`, since "stable" Spacemacs is a 3-4 years back time machine and "stable" docs largely not maintained & out of date, because all maintainers and community lives on the `develop`

Spacemacs "stable" is essentially abandoned (the last major stable release was >4 years ago (Version 0.200.0 - Oct 5, 2016, last minor release Version 0.200.13 - Jan 25, 2018 - that is almost 3 years to the current date). `syl20bnr` gives-up stubbornness very slowly, even with such things as keeping the `develop` brunch in the back & the "stable" (frozen) `master` branch ([link](https://github.com/syl20bnr/spacemacs/tree/master)) upfront and for ~3 years. People used to arrive at the project frontpage ([link](https://github.com/syl20bnr/spacemacs/tree/master)) and be puzzled - looking at the branch activity - is a project even alive? (and the activity graphs were showing the frozen `master` branch also - it was in effect for 3 years.
So eventually the representative branch was switched to `develop`. But the situation keeps, two-fold. I and many (probably most Spacemacs users) use `https://develop.spacemacs.org/` as Spacemacs, but there is also 3 years old `master` branch that is still advertised:

>3 years ago I smartly sneaked-in the `develop` reference so the `syl20bnr` would merge it into the project GitHub front page:
```
For stable releases:

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

For development updates and participation:

git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```
It is still the same reference, so creator still advertises the frozen branch first as a stable release. With that decigion goes the: `https://spacemacs.org/`.

IDK why Spacemacs so far not switched instructions & front-facing docs to the state of affairs in the distro. `syl20bnr` gave up front facing branch, but not waterfall model release dream, Spacemacs front buffer presents everyone with:
```
|                         VERSION 0.300 IS ALMOST OUT!                               │
```

That threat to form stable hangs there 1 month less than I use Spacemacs (for 3.5 years). I gave waiting for stable releases after a 0.5-1 year of use and as others - switched to `develop` aka the rolling world.

Lets just say `syl20bnr` is stubborn to admit the stable release in such wast rolling community process is not possible.

So that is only to explain why URL is to `https://develop.spacemacs.org/`.

**Comment by yihuajack** [comment]
Thanks for suggestion, updated

**Comment by Anton-Latukha** [comment]
And I am sorry for hijacking the thread, just a drive-by thing.

It feels really dirty to come like this and write in other people's PRs.

**Pull request merged**
